[tool.poetry]
name = "pyminthcm"
version = "0.1.0"
description = ""
authors = ["evolpeAI"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
oauthlib = "^3.2.2"
requests-oauthlib = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
